### ISSUE TITLE
How about a installing a cli bin named uuid?

### ISSUE THREAD

**Issue by detj** [defunctzombie/node-uuid#10]
Would be easier to create random one off UUIDs on an ad hoc basis.

**Comment by defunctzombie** [comment]
I'd be more inclined it being a separate module or whatnot since the majority use case is as a library. Agreed that it is nice to generate uuid from cli; on osx I use the `uuidgen` command (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/uuidgen.1.html) which I think also exists on linux systems.
