### ISSUE TITLE
Can't pull in `node-uuid` via a `<script>` tag

### ISSUE THREAD

**Issue by nick-woodward** [defunctzombie/node-uuid#23]
### Description

It seems that at some point `node-uuid` ended up dropping support to pull it in via a `<script>` tag.

It should also be noted that the README claims this can be pulled in via a `<script>` tag.
### Example

**[Live Demo](http://jsbin.com/nojapapuci/edit?html,console)** (Open up the devtools for more info)
### Possible Solutions
- Utilize a bundler like Webpack **(Recommended)**
- Check if `require` is available before attempting to `require`

**Comment by defunctzombie** [comment]
Yep, the readme should be fixed to reflect that you can't just use it in a script tag. You either need a bundler or use a CDN that does automatic npm module bundling.

**Comment by leftclickben** [comment]
This is also an issue for me.  I am installing via `bower` and using `requirejs` to load modules, but there is no support at all for it.  Please use a UMD pattern (e.g. https://gist.github.com/kitcambridge/1251221) so that it can be loaded via script tag, AMD or NPM style loader.  I am not going to introduce `browserify` just for one library, so I think my only option is to use a different UUID module, which is a shame because I'm already using this one on the server side.

**Comment by nick-woodward** [comment]
It should also be noted that this makes it quite a bit more difficult to use `node-uuid` with polymer.

I'm guessing its possible to do so with a bundler, but it seems a bit silly to add a bundler just for `node-uuid`.

**Comment by defunctzombie** [comment]
project has moved here and is being consolidated with node-uuid module https://github.com/kelektiv/node-uuid
